language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
branches:
  only:
  - master 
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
  - ./scripts/test.sh
notifications:
  email:
    on_success: never
on_failure: always