language: csharp
dist: trusty
mono: none
dotnet: 2.2
branches:
  only:
    - master 
script:
  - ./scripts/travis-build.sh
  - ./scripts/test.sh
notifications:
  email:
    on_success: never
on_failure: always